import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../core/constants/app_colors.dart';
import '../../gen/assets.gen.dart';
import 'custom_button.dart';
import 'custom_checkbox_widget.dart';
import 'custom_text_field.dart';

class LoginResetPasswordWidgetBuilder {
  static Widget _buildBody({
    required double loginFontSize,
    required double topPadding,
    required double termsFont,
    termsFont2,
    required double buttonHeight,

    required suffixIconPadding,
    required EdgeInsetsGeometry termsPadding,
    required double sizedBoxHeight,
    required double generalErrorFont,
    bool? value,

    required EdgeInsetsGeometry? contentPadding1,
    contentPadding2,
    double? sizedBoxHeight1,
    void Function(String)? onChanged1,
    void Function(String)? onChanged2,
    required void Function()? onPressed,

    GlobalKey<FormState>? formKey,

    void Function(bool?)? termsOnChanged,
    TextEditingController? controller1,
    TextEditingController? controller2,

    bool firstFieldHasError = false,
    bool secondFieldHasError = false,
    Widget? suffixIcon,
    String? titleText,
    String? errorMessage1,
    String? errorMessage2,
    AutovalidateMode? autoValidateMode,
    labelText1,
    labelText2,
    hintText1,
    hintText2,
    bool isPassword = false,
    bool showRichText = true,
    buttonText,
    textFieldIcon,
    double? footerTextFontSize,
    void Function()? resetPassword,
    void Function()? signup,
    double? signUpFontSize,
  }) {
    return Column(
      children: [
        Text(
          titleText ?? 'Login',
          textAlign: TextAlign.center,
          style: GoogleFonts.hind(
            fontSize: loginFontSize,
            fontWeight: FontWeight.w700,
            color: AppColors.textVidaLocaGreen,
          ),
        ),
        const SizedBox(height: 20.0),
        CustomTextField(
          label: labelText1 ?? 'Email',
          iconHeight: 18,
          iconWidth: 18,
          prefixIcon: textFieldIcon ?? AppAssets.icons.mail.path,
          hintText: hintText1 ?? 'Enter your email',
          hintTextColor: AppColors.textIconGrey,
          controller: controller1,
          hasError: firstFieldHasError,
          suffixIcon: suffixIcon,
          isPassword: isPassword,
          labelFontWeight: FontWeight.w600,
          suffixIconPadding: suffixIconPadding,
          contentPadding: contentPadding1,
          errorMessage: errorMessage1,
          onChanged: onChanged1,
        ),
        const SizedBox(height: 25.0),
        CustomTextField(
          label: labelText2 ?? 'Password',
          isPassword: true,
          iconHeight: 18,
          iconWidth: 18,
          prefixIcon: AppAssets.icons.lock.path,
          hintText: hintText2 ?? 'Enter your password',
          hintTextColor: AppColors.textIconGrey,
          suffixIcon: Icon(Icons.visibility_outlined),
          controller: controller2,
          suffixIconPadding: suffixIconPadding,
          hasError: secondFieldHasError,
          labelFontWeight: FontWeight.w600,
          contentPadding: contentPadding2,
          errorMessage: errorMessage2,
          onChanged: onChanged2,
        ),
        SizedBox(height: 12.0),
        showRichText
            ? InkWell(
                onTap: resetPassword,
                child: Align(
                  alignment: Alignment.centerLeft,
                  child: Text(
                    "Forgot Password?",
                    style: GoogleFonts.hind(
                      fontSize: footerTextFontSize,
                      fontWeight: FontWeight.w400,
                      color: AppColors.textOrange,
                    ),
                  ),
                ),
              )
            : Padding(
                padding: termsPadding,
                child: Row(
                  children: [
                    CustomCheckBox(
                      sizedBoxHeight: sizedBoxHeight,
                      value: value ?? false,
                      onChanged: termsOnChanged,
                    ),
                    const SizedBox(width: 14),
                    Expanded(
                      child: Text(
                        "Remember me",
                        style: GoogleFonts.hind(
                          fontSize: termsFont2,
                          fontWeight: FontWeight.w400,
                          color: AppColors.textBlackGrey,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
        const SizedBox(height: 44.0),
        CustomButton(
          text: buttonText ?? 'Login',
          onPressed: onPressed,
          fontSize: 18,
          fontWeight: FontWeight.w500,
          height: buttonHeight,
          width: double.infinity,
          padding: EdgeInsets.zero,
        ),
        if (showRichText) ...[
          const SizedBox(height: 10),
          RichText(
            text: TextSpan(
              children: [
                TextSpan(
                  text: "Want to create an account? ",
                  style: GoogleFonts.hind(
                    fontSize: signUpFontSize,
                    fontWeight: FontWeight.w400,
                    color: AppColors.textBlackGrey,
                  ),
                ),
                TextSpan(
                  text: "Sign up",
                  style: GoogleFonts.hind(
                    fontSize: signUpFontSize,
                    fontWeight: FontWeight.w600,
                    color: AppColors.textOrange,
                  ),
                  recognizer: TapGestureRecognizer()..onTap = signup,
                ),
              ],
            ),
          ),
        ],
        SizedBox(height: sizedBoxHeight1 ?? 24),
      ],
    );
  }

  static Widget buildMobileBody({
    required void Function()? onPressed,
    required EdgeInsetsGeometry contentPadding1,
    void Function(String)? onChanged1,
    void Function(String)? onChanged2,
    bool firstFieldHasError = false,
    bool secondFieldHasError = false,
    GlobalKey<FormState>? formKey,
    bool? value,
    void Function(bool?)? termsOnChanged,
    String? Function(String?)? validator1,
    String? Function(String?)? validator2,
    String? errorMessage1,
    String? errorMessage2,
    AutovalidateMode? autoValidateMode,
    TextEditingController? controller1,
    TextEditingController? controller2,
    Widget? suffixIcon,
    String? titleText,
    labelText1,
    labelText2,
    hintText1,
    hintText2,
    bool isPassword = false,
    bool showRichText = true,
    buttonText,
    textFieldIcon,
    void Function()? resetPassword,
    void Function()? signUp,
  }) => _buildBody(
    value: value,
    signup: signUp,
    signUpFontSize: 12,
    footerTextFontSize: 14,
    loginFontSize: 20.0,
    topPadding: 0.0,
    termsFont: 10.0,
    buttonHeight: 45.0,
    suffixIconPadding: 10.0,
    termsPadding: EdgeInsets.zero,
    sizedBoxHeight: 11.0,
    generalErrorFont: 15.0,
    termsFont2: 12.0,
    contentPadding1: contentPadding1,
    contentPadding2: EdgeInsets.only(top: 13.8),
    onPressed: onPressed,
    firstFieldHasError: firstFieldHasError,
    secondFieldHasError: secondFieldHasError,
    controller1: controller1,
    controller2: controller2,
    formKey: formKey,
    suffixIcon: suffixIcon,
    hintText1: hintText1,
    hintText2: hintText2,
    titleText: titleText,
    labelText1: labelText1,
    labelText2: labelText2,
    showRichText: showRichText,
    isPassword: isPassword,
    buttonText: buttonText,
    termsOnChanged: termsOnChanged,
    textFieldIcon: textFieldIcon,
    errorMessage1: errorMessage1,
    errorMessage2: errorMessage2,
    autoValidateMode: autoValidateMode,
    onChanged1: onChanged1,
    onChanged2: onChanged2,
    resetPassword: resetPassword,
  );

  static Widget buildWebBody({
    bool? value,
    required void Function()? onPressed,
    void Function(String)? onChanged1,
    void Function(String)? onChanged2,
    bool firstFieldHasError = false,
    bool secondFieldHasError = false,
    GlobalKey<FormState>? formKey,
    required EdgeInsetsGeometry? contentPadding1,
    void Function(bool?)? termsOnChanged,
    TextEditingController? controller1,
    TextEditingController? controller2,
    Widget? suffixIcon,
    String? titleText,
    String? errorMessage1,
    String? errorMessage2,
    AutovalidateMode? autoValidateMode,
    labelText1,
    labelText2,
    hintText1,
    hintText2,
    bool isPassword = false,
    bool showRichText = true,
    buttonText,
    textFieldIcon,
    void Function()? resetPassword,
    void Function()? signUp,
  }) => _buildBody(
    value: value,
    signup: signUp,
    resetPassword: resetPassword,
    loginFontSize: 36.0,
    footerTextFontSize: 16.0,
    signUpFontSize: 16,
    topPadding: 0.0,
    termsFont: 16.0,
    buttonHeight: 50.0,
    termsPadding: EdgeInsets.only(left: 5.0),
    sizedBoxHeight: 11.0,
    sizedBoxHeight1: 34.0,
    termsFont2: 16.0,
    suffixIconPadding: 25.0,
    generalErrorFont: 16.0,
    contentPadding1: contentPadding1,
    contentPadding2: EdgeInsets.only(top: 14.0),
    onPressed: onPressed,
    onChanged1: onChanged1,
    onChanged2: onChanged2,
    firstFieldHasError: firstFieldHasError,
    secondFieldHasError: secondFieldHasError,
    controller1: controller1,
    controller2: controller2,
    formKey: formKey,
    suffixIcon: suffixIcon,
    hintText1: hintText1,
    hintText2: hintText2,
    titleText: titleText,
    labelText1: labelText1,
    labelText2: labelText2,
    showRichText: showRichText,
    isPassword: isPassword,
    buttonText: buttonText,
    textFieldIcon: textFieldIcon,
    termsOnChanged: termsOnChanged,
    autoValidateMode: autoValidateMode,
    errorMessage1: errorMessage1,
    errorMessage2: errorMessage2,
  );
}
